services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - agent

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    # Create agent/.env from agent/.env.example and set required keys before running
    env_file:
      - agent/.env
